## Add this file to your meteor package as `.travis.yml`
env: TEST_COMMAND=./travis.sh
sudo: required
language: node_js
node_js:
  # - "0.8"
  - "0.10"
  - "0.12"

before_install:
  - "curl -L http://git.io/ejPSng | /bin/sh"